
BOOST_INCS = /home/vkuchuk/proj/boost/
BOOST_OBJ_DIR=/home/vkuchuk/proj/boost/stage/lib/

CXXFLAGS+=-std=c++11 -g -I$(BOOST_INCS) -Wall

LDFLAGS+= -L$(BOOST_OBJ_DIR) -Wl,-rpath=$(BOOST_OBJ_DIR) -lpthread -lboost_locale -lboost_program_options -licuuc -licuio

all: xmlparser statechart task_queue progopt

xmlparser:

statechart:

task_queue:

progopt:

