LIB_PATH = /home/vkuchuk/proj/epiphan_svn_trunk/epiphan/vga2cpu/ltib/vga2web/src
LIBLOG_PATH = $(LIB_PATH)/liblog/liblog/lib/
LIBLOG_INC = $(LIB_PATH)/liblog/liblog/
LIBOBJ_PATH = $(LIB_PATH)/libobjstream/libobjstream/lib/
LIBOBJ_INC = $(LIB_PATH)/libobjstream/libobjstream/include

#LDFLAGS = -L$(LIBLOG_PATH) -L$(LIBOBJ_PATH) -llog -lobjstream 
#CPPFLAGS = -I$(LIBLOG_INC) -I$(LIBOBJ_INC) -g -std=c++11
CPPFLAGS = -g -std=c++11

main: log.o
